
from __future__ import annotations

from rest_framework import serializers

from .models import AuditLog


class AuditLogSerializer(serializers.ModelSerializer):
    """
    Read-only serializer for security audit events.

    Audit records are generated by the backend and cannot be
    modified through the API.
    """

    user_id = serializers.CharField(
        source="user.user_id",
        read_only=True,
    )

    user_email = serializers.EmailField(
        source="user.email",
        read_only=True,
    )

    class Meta:
        model = AuditLog

        fields = [
            "id",
            "user_id",
            "user_email",
            "action",
            "ip_address",
            "user_agent",
            "resource",
            "resource_id",
            "description",
            "status",
            "created_at",
        ]

        read_only_fields = [
            "id",
            "user_id",
            "user_email",
            "action",
            "ip_address",
            "user_agent",
            "resource",
            "resource_id",
            "description",
            "status",
            "created_at",
        ]
