# Generated by Django 6.1.1 on 2026-09-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('FAILED_LOGIN', 'Failed Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('CAPTCHA_FAILED', 'Captcha Failed'), ('THREAT_ANALYZED', 'Threat Analyzed'), ('PHISHING_SCAN', 'Phishing Scan'), ('URL_BLOCKED', 'URL Blocked'), ('EMAIL_QUARANTINED', 'Email Quarantined'), ('IMPERSONATION_DETECTED', 'Impersonation Detected'), ('DEEPFAKE_DETECTED', 'Deepfake Detected'), ('ANOMALY_DETECTED', 'Anomaly Detected'), ('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_UPDATED', 'Incident Updated'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('SESSION_REVOKED', 'Session Revoked'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('SETTINGS_CHANGED', 'Settings Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='SUCCESS', max_length=20),
        ),
    ]
