# Generated by Django 6.1.1 on 2026-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('FAILED_LOGIN', 'Failed Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_SUCCESS', 'Password Reset Success'), ('CAPTCHA_FAILED', 'Captcha Failed'), ('THREAT_ANALYZED', 'Threat Analyzed'), ('PHISHING_SCAN', 'Phishing Scan'), ('URL_BLOCKED', 'URL Blocked'), ('EMAIL_QUARANTINED', 'Email Quarantined'), ('IMPERSONATION_DETECTED', 'Impersonation Detected'), ('DEEPFAKE_DETECTED', 'Deepfake Detected'), ('ANOMALY_DETECTED', 'Anomaly Detected'), ('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_UPDATED', 'Incident Updated'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('SESSION_REVOKED', 'Session Revoked'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('SETTINGS_CHANGED', 'Settings Changed')], max_length=50),
        ),
    ]
