# Generated by Django 6.1.1 on 2026-09-12 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('result', models.CharField(choices=[('SAFE', 'Safe'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='SAFE', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpersonationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=100)),
                ('evidence_value', models.TextField(blank=True)),
                ('risk_contribution', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='impersonation.impersonationscan')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_match_indicator', models.BooleanField(default=False)),
                ('face_swap_indicator', models.BooleanField(default=False)),
                ('suspicious_face_region', models.BooleanField(default=False)),
                ('visual_mismatch_indicator', models.BooleanField(default=False)),
                ('impersonation_indicators', models.JSONField(blank=True, default=list)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_analysis', to='impersonation.impersonationscan')),
            ],
        ),
        migrations.CreateModel(
            name='DeepfakeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_detected', models.BooleanField(default=False)),
                ('multiple_faces', models.BooleanField(default=False)),
                ('face_manipulation_indicator', models.BooleanField(default=False)),
                ('lighting_inconsistency', models.BooleanField(default=False)),
                ('edge_artifact_indicator', models.BooleanField(default=False)),
                ('compression_anomaly', models.BooleanField(default=False)),
                ('metadata_missing', models.BooleanField(default=False)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deepfake_analysis', to='impersonation.impersonationscan')),
            ],
        ),
    ]
