# Generated by Django 6.1.1 on 2026-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impersonation', '0003_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impersonationevidence',
            name='evidence_value',
            field=models.TextField(blank=True),
        ),
    ]
