# Generated by Django 6.1.1 on 2026-09-23 07:53

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_browser_privacy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='browserprivacypairing',
            new_name='security_br_user_id_81d0e2_idx',
            old_name='security_br_user_id_2a2a8e_idx',
        ),
        migrations.RenameIndex(
            model_name='browserprivacyscan',
            new_name='security_br_user_id_5b96ea_idx',
            old_name='security_br_user_id_9c3e8b_idx',
        ),
        migrations.AlterField(
            model_name='browserprivacyscan',
            name='cookie_metadata',
            field=security.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='browserprivacyscan',
            name='extension_metadata',
            field=security.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='browserprivacyscan',
            name='summary',
            field=security.fields.EncryptedJSONField(blank=True, default=dict),
        ),
    ]
