# Generated by Django 6.1.1 on 2026-09-12 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('URL', 'URL'), ('EMAIL', 'Email')], max_length=20)),
                ('input_data', models.TextField()),
                ('risk_score', models.FloatField(default=0)),
                ('result', models.CharField(choices=[('SAFE', 'Safe'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='SAFE', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phishing_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('has_suspicious_keyword', models.BooleanField(default=False)),
                ('has_urgent_language', models.BooleanField(default=False)),
                ('has_suspicious_link', models.BooleanField(default=False)),
                ('has_attachment_warning', models.BooleanField(default=False)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_analysis', to='phishing.phishingscan')),
            ],
        ),
        migrations.CreateModel(
            name='URLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('uses_https', models.BooleanField(default=False)),
                ('url_length', models.PositiveIntegerField(default=0)),
                ('has_ip_address', models.BooleanField(default=False)),
                ('has_suspicious_keyword', models.BooleanField(default=False)),
                ('has_shortener', models.BooleanField(default=False)),
                ('redirect_count', models.PositiveIntegerField(default=0)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_analysis', to='phishing.phishingscan')),
            ],
        ),
    ]
