# Generated by Django 6.1.1 on 2026-09-12 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('PHISHING', 'Phishing'), ('MALICIOUS_URL', 'Malicious URL'), ('SUSPICIOUS_EMAIL', 'Suspicious Email'), ('SUSPICIOUS_MESSAGE', 'Suspicious Message'), ('DEEPFAKE', 'Deepfake'), ('IMAGE_MANIPULATION', 'Image Manipulation'), ('ANOMALY', 'Anomaly'), ('ACCOUNT_TAKEOVER', 'Account Takeover'), ('MALICIOUS_FILE', 'Malicious File'), ('NETWORK_THREAT', 'Network Threat'), ('OTHER', 'Other')], max_length=50)),
                ('source_type', models.CharField(choices=[('URL', 'URL'), ('EMAIL', 'Email'), ('MESSAGE', 'Message'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('LOGIN', 'Login Activity'), ('DEVICE', 'Device Activity'), ('NETWORK', 'Network Activity'), ('FILE', 'File'), ('OTHER', 'Other')], max_length=30)),
                ('input_data', models.TextField(blank=True)),
                ('risk_score', models.FloatField(default=0)),
                ('severity', models.CharField(choices=[('SAFE', 'Safe'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='SAFE', max_length=20)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='DETECTED', max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='threat_detection.threat')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=100)),
                ('evidence_value', models.TextField(blank=True)),
                ('risk_contribution', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='threat_detection.threat')),
            ],
        ),
    ]
